# Generated by Django 5.2.4 on 2025-08-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='connect.developerprofile')),
            ],
        ),
    ]
