# Generated by Django 5.2.4 on 2025-08-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_remove_developerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='email',
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='skills',
            field=models.CharField(default='maria@yousaf.com', max_length=255),
            preserve_default=False,
        ),
    ]
